python src/run_translation.py \
    --model_name facebook/nllb-200-distilled-1.3B \
    --src_lang ind \
    --tgt_lang btx \
    --src_lang_nllb ind_Latn \
    --tgt_lang_nllb btx_Latn \
    --source_text_column_name text_source \
    --target_text_column_name text_target \
    --max_length 256 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --learning_rate 1e-4 \
    --weight_decay 0.01 \
    --num_train_epochs 20 \
    --early_stopping_patience 3